import type { Metadata } from "next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Inter, Montserrat } from "next/font/google";
const mont = Montserrat({ subsets: ["latin"] });
import LayoutDefault from "./_layouts/layoutDefault";
import "./globals.css";

export const metadata: Metadata = {
  title: "E-commerce",
  description: "E-commerce app generated by create next app",
};

export default async function RootLayout({
  children,
  modals,
}: {
  children: React.ReactNode;
  modals: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={mont.className}>
        <SpeedInsights />
        <LayoutDefault>
          {children}
          {modals}
        </LayoutDefault>
      </body>
    </html>
  );
}
