import type { Metadata } from "next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Montserrat } from "next/font/google";
const mont = Montserrat({ subsets: ["latin"] });
import LayoutDefault from "./_layouts/layoutDefault";
import "./globals.css";
import AppContextProvider from "./contexts";
import StoreProvider from "./StoreProvider";

export const metadata: Metadata = {
  title: "Mery's Glam",
  description: "E-commerce app generated by create next app",
};

export default function RootLayout({
  children,
  modals,
}: {
  children: React.ReactNode;
  modals: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          type="image/png"
          href="/favicon-96x96.png"
          sizes="96x96"
        />
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
        <link rel="shortcut icon" href="/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
      </head>
      <body className={`${mont.className}`}>
        <SpeedInsights />
        <StoreProvider>
          <AppContextProvider>
            <LayoutDefault>
              {children}
              {modals}
            </LayoutDefault>
          </AppContextProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
