import type { Metadata } from "next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Montserrat } from "next/font/google";
const mont = Montserrat({ subsets: ["latin"] });
import LayoutDefault from "./_layouts/layoutDefault";
import "./globals.css";
import AppContextProvider from "./contexts";

export const metadata: Metadata = {
  title: "E-commerce",
  description: "E-commerce app generated by create next app",
};

export default async function RootLayout({
  children,
  modals,
  cart,
}: {
  children: React.ReactNode;
  modals: React.ReactNode;
  cart: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={mont.className}>
        <SpeedInsights />
        <AppContextProvider>
          <LayoutDefault>
            {children}
            {modals}
            {cart}
          </LayoutDefault>
        </AppContextProvider>
      </body>
    </html>
  );
}
